build:
  gpu: true
  cuda: "11.8"
  python_version: "3.10"
  system_packages:
    - "build-essential"
    - "git"
  python_packages:
    - "torch>=2.0.0"
    - "transformers>=4.30.0"
    - "peft>=0.4.0"
    - "accelerate>=0.20.0"
    - "bitsandbytes>=0.41.0"
    - "fastapi>=0.100.0"
    - "uvicorn>=0.22.0"
    - "pydantic>=2.0.0"
    - "sentencepiece>=0.1.99"
    - "protobuf>=4.23.0"
    - "numpy>=1.24.0"
    - "pandas>=2.0.0"
    - "scikit-learn>=1.2.0"
    - "tqdm>=4.65.0"
    - "wandb>=0.15.0"
    - "faiss-cpu>=1.7.4"
    - "sentence-transformers>=2.2.0"

deploy:
  target: "spaces"
  hardware:
    cpu: 4
    memory: 16
    gpu: "T4"
  port: 7860
  health_check: "/"
  env:
    - name: "HF_HOME"
      value: "/app/data/models"
    - name: "PYTHONPATH"
      value: "/app" 